const COOKIE_PREFIX = "jlr_defectlens_dashboard";

const APP_PREFIX = "JLR";
const APP_NAME = "EPMC DefectLens";
const APP_FULL_NAME = `${APP_NAME}`;
const APP_DESCRIPTION = "";
const PLANT_NAME = "EPMC";

const THEME_COOKIE_NAME = `${COOKIE_PREFIX}-theme:state`;
const THEME_COOKIE_MAX_AGE = 60 * 60 * 24 * 7 * 365; // 1 year

const SIDEBAR_COOKIE_NAME = `${COOKIE_PREFIX}-sidebar:state`;
const SIDEBAR_COOKIE_MAX_AGE = 60 * 60 * 24 * 7;

export { APP_DESCRIPTION, APP_FULL_NAME, APP_NAME, APP_PREFIX, COOKIE_PREFIX, PLANT_NAME, SIDEBAR_COOKIE_MAX_AGE, SIDEBAR_COOKIE_NAME, THEME_COOKIE_MAX_AGE, THEME_COOKIE_NAME };
